"""Initial migration test by Line

Revision ID: 79b91fd252f4
Revises: 
Create Date: 2023-01-27 12:29:43.015975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b91fd252f4'
down_revision = None
branch_labels = None
depends_on = None

# convention = {
#     "ix": 'ix_%(column_0_label)s',
#     "uq": "uq_%(table_name)s_%(column_0_name)s",
#     "ck": "ck_%(table_name)s_%(constraint_name)s",
#     "fk": "fk_%(table_name)s_%(referred_table_name)s_%(column_0_name)s",
#     "pk": "pk_%(table_name)s"
# }


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_contact_gender_gender_id'), 'gender', ['gender_id'], ['id'])

    with op.batch_alter_table('gender', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gender', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_contact_gender_gender_id'), type_='foreignkey')
        batch_op.drop_column('gender_id')

    # ### end Alembic commands ###
